name: CI

on:
    workflow_dispatch:
    push:
        branches: ["main","fix-worflow"]
    pull_request:
        branches: ["main"]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Hello World"


  test:
    runs-on: ubuntu-latest
    needs: hello

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry install --no-interaction --no-ansi
      - run: poetry run pytest